# Generated by Django 2.2.5 on 2019-09-05 22:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 5, 22, 33, 49, 923431, tzinfo=utc)),
        ),
    ]
