# Generated by Django 2.2.5 on 2019-09-06 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190905_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 20, 31, 11, 26019, tzinfo=utc)),
        ),
    ]
