# Generated by Django 2.2.5 on 2019-09-09 05:50

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190906_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default='https://open.spotify.com/artist/6fC2AcsQtd9h4BWELbbire?si=b-CaWJZdSP-FF_6i-havdA', help_text='Must be a Spotify link; sorry Apple users.', max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid link.', regex='(https://open.spotify.com/){1}(track|album|artist){1}/.*')]),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Tell us about it!'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Song, Album, or Artist'),
        ),
    ]
