# Generated by Django 2.2.5 on 2019-09-09 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190908_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'Song'), (2, 'Album'), (3, 'Artist')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(help_text="URL format: 'https://open.spotify.com/(track|album|artist)/.*'", max_length=100, validators=[django.core.validators.RegexValidator(message='Please enter a valid link.', regex='(https://open.spotify.com/){1}(track|album|artist){1}/.*')], verbose_name='Spotify Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
