# Generated by Django 2.2.5 on 2019-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190909_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Song', 'Song'), ('Album', 'Album'), ('Artist', 'Artist')], max_length=50),
        ),
    ]
