# Generated by Django 2.2.5 on 2019-09-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190910_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_set',
            field=models.BooleanField(default=False),
        ),
    ]
