# Generated by Django 2.2.5 on 2019-09-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_tags_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags_set',
        ),
    ]
